"""
This code is generated by Alimul Haque Khan, with help of chatGPT.

You are free to use, modify, and distribute this code without any obligation to provide credit to the original author.

The author of this code makes no warranties or guarantees regarding its functionality, reliability, or suitability for any purpose. 
Use it at your own risk.

If you find this code helpful, you are encouraged but not required to acknowledge the original author.

For more information, visit https://www.linkedin.com/in/ah-khan/
"""


import os
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib as mpl
from wordcloud import WordCloud, STOPWORDS


import pdfplumber

def convert_pdf_to_txt(pdf_path, txt_path):
    with pdfplumber.open(pdf_path) as pdf:
        with open(txt_path, "w", encoding="utf-8") as txt_file:
            for page in pdf.pages:
                text = page.extract_text()
                txt_file.write(text)

# Provide the input PDF file path and output TXT file path
# pdf_file = "Article.pdf"
pdf_file = "IoT.pdf"
txt_file = "Article.txt"

# Call the conversion function
convert_pdf_to_txt(pdf_file, txt_file)



# Get the current working directory
current_dir = os.getcwd()


Article_file = os.path.join(current_dir, 'Article.txt')

with open(Article_file, 'r') as file:    Article = file.read()


# Defining stopwords
stopwords = set(STOPWORDS)
print('Stopwords:', stopwords)

# Instantiating the word cloud objects
Article_wc = WordCloud(background_color='white', max_words=100, stopwords=stopwords, scale=1, width=1600, height=800)

# Generating the word clouds
Article_wc.generate(Article)

# Saving the word clouds as .png files
Article_output_file = os.path.join(current_dir, 'Article_WC.png')


Article_wc.to_file(Article_output_file)
